### ISSUE TITLE
no CONTRIBUTORS file

### ISSUE THREAD

**Issue by wellsjo** [maandree/blueshift#14]

**Comment by jwerle** [comment]
+1

**Comment by jwerle** [comment]
cc @stephenmathieson

**Comment by humanshell** [comment]
+1

**Comment by maandree** [comment]
But noone has contributed. Well, at least no the form of code, just a ideas.

**Comment by maandree** [comment]
For significant help I create a ACKNOWLEDGEMENT file.
For significant contribution I add them to COPYING.
For trivial contributions, their existing is `git log` is sufficient.
