### ISSUE TITLE
Hello there

### ISSUE THREAD

**Issue by stefan430** [maandree/blueshift#17]
I'm a newbie to linux, and I saw that your program has the ''darkroom mode'' option, which I always use when I'm using Windows. I have installed it via yaourt on antergos, but I don't know how to start it up in the terminal, or to say, how to ''open it'' so I can use the options. I saw you have provided information how to set up the darkroom mode, I just don't know with what to begin with.

Thankful for any information.

**Comment by maandree** [comment]
`blueshift -c /usr/share/doc/blueshift/examples/darkroom` starts darkroom mode. If you are going to use it often I suggest making an alias for it, by adding the line `alias darkroom='blueshift -c /usr/share/doc/blueshift/examples/darkroom'` to `~/.bashrc` (assuming you are using Bash). Alternatively you can add create the file `/usr/local/bin/darkroom` containing
```sh
#!/bin/sh
blueshift -c /usr/share/doc/blueshift/examples/darkroom
```
(don't forget to run `chmod a+x /usr/local/bin/darkroom` to make it executable. If you do either of these, you can just run `darkroom` to start darkroom mode.

I would suggest that you look into [cg-tools](https://github.com/maandree/cg-tools), which also has darkroom mode. All programs in cg-tools can run at the same time, however, I've written a colour temperature program yet, but I will do that later as well as make blueshift compatible. There is however a [patch](https://github.com/jonls/redshift/pull/410) for redshift which makes redshift compatible with cg-tools.

**Comment by stefan430** [comment]
Thank you for the comprehensive answer.

> I've written a colour temperature program yet
I guess you wanted to type '' haven't '' ?
Darkroom mode in cg-tools works beautifully. One thing though. When I type in cg-remove it asks me ''Usage: cg-remove [-M method] [-S site] [-c crtc]... class...'' aaand when I want to remove a filter, say darkroom mode, I type what exactly... ?

When I run blueshift -c /usr/share/doc/blueshift/examples/darkroom in the terminal, it shows the following: 
Warning: failed to load module 'argparser',
         command line options will not be parsed.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/blueshift/__main__.py", line 95, in <module>
  File "/usr/bin/blueshift/solar.py", line 20, in <module>
ModuleNotFoundError: No module named 'solar_python'

I checked, I havet both solar python and argparser installed. What's the catch?

**Comment by maandree** [comment]
Yes, that's what I meant.

To remove the darkroom filter, just type `darkroom -x`.
`cg-query` and `cg-remove` are advanced tools that your will probably never use except for debugging.

Check that you have the python version of argparser installed.

**Comment by stefan430** [comment]
argparser  5.1-5
solar-python  2.5-1
These are the versions I have.

I already have libcoopgamma installed, how do I use the patch?

**Comment by maandree** [comment]
Are you using Archlinux? If so, install the package argparser-python, blueshift should depend on it, but perhaps it's missing.

To use the patch for redshift:
```sh
git clone https://github.com/jonls/redshift/ redshift-coopgamma
cd redshift-coopgamma
git remote add maandree https://github.com/maandree/redshift/
git fetch maandree
git pull . maandree/coopgamma
./bootstrap
./configure --prefix=/usr --with-systemduserunitdir=/usr/lib/systemd/user
make
sudo make install
```
If you do this while redshift is installed, it will replace existing files and can be uninstalled by uninstalling the already installed redshift package.
