### ISSUE TITLE
arch No configuration file found

### ISSUE THREAD

**Issue by joksik** [maandree/blueshift#18]
hello i install blueshift on arch using aur but when i want start i have this error:

`No configuration file found`

and dont see in description on github that i must create some file?

**Comment by maandree** [comment]
You need $XDG_CONFIG_HOME/blueshift/blueshiftrc, $HOME/.config/blueshift/blueshiftrc, $HOME/.blueshiftrc or /etc/blueshiftrc, or a file specified by the -c flag. In /usr/share/doc/blueshift/examples/ you will find example configurations. I recommend starting with using `/usr/share/doc/blueshift/examples/comprehensive` as your config file, with the line starting with `latitude, longitude =` adjusted for your location.

**Comment by joksik** [comment]
thx for quick replay i am beginner in linux so i think that i must copy comprehensive file from /usr/share/doc/blueshift/examples/ into /home/.config/blueshift and start by command:

blueshift -c /home/.config/blueshift/comprehensive

that correct?

**Comment by maandree** [comment]
That will work, but if you name it `blueshiftrc`, you do need the -c flag.

```sh
mkdir ~/.config/blueshift
cp /usr/share/doc/blueshift/examples/comprehensive ~/.config/blueshift/blueshiftrc
blueshift
```

But don't forget to edit the file, otherwise (unless you live near Stockholm) the colour temperature be adjusted as expected.

**Comment by joksik** [comment]
thanks a lot! i see in config file that blueshift will start up at 22:00?? so after few minutes and i will test it ;)

my location from http://www.geonames.org/ is:

N 52° 39' 55''	E 19° 3' 38'' 

so i must only change latitude, longitude to 52.3955 19.0338 and that all ?

**Comment by maandree** [comment]
The 22:00 part is not use by default, but can be selected further down in the file.
If you run `blueshift -p` the effect will take place immediately, it is a good way to
test that everything works.

`latitude` and `longitude` are specified in decimal, so it would be
`latitude, longitude = 52.665278, 19.060556`

**Comment by joksik** [comment]
i was wonder why it`s not working but now i see what you write that latitude and longitue are in decmial. ok i will fix it in my config. 

blueshift start with no error but when i done blueshift -p nothing happen with my laptop screen. i must edit something else in config file? i use laptop with single intel 520 graphic card
